"""esquema inicial

Revision ID: 9adf5c7f9715
Revises: 
Create Date: 2026-08-08 02:30:53.076551

"""
from alembic import op
import sqlalchemy as sa


revision = '9adf5c7f9715'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('particular', 'comercio', 'industria', name='tipocliente'), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('localidad', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'en_riesgo', 'inactivo', name='estadocliente'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_estado'), 'clientes', ['estado'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nombre'), 'clientes', ['nombre'], unique=False)
    op.create_table('etiquetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etiquetas_id'), 'etiquetas', ['id'], unique=False)
    op.create_index(op.f('ix_etiquetas_nombre'), 'etiquetas', ['nombre'], unique=True)
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicios_id'), 'servicios', ['id'], unique=False)
    op.create_table('tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tecnicos_id'), 'tecnicos', ['id'], unique=False)
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('frecuencia', sa.Enum('semanal', 'quincenal', 'mensual', 'trimestral', 'semestral', 'anual', 'a_demanda', name='frecuenciacontrato'), nullable=False),
    sa.Column('precio_acordado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_cliente_id'), 'contratos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_contratos_id'), 'contratos', ['id'], unique=False)
    op.create_table('trabajos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('fecha_programada', sa.Date(), nullable=False),
    sa.Column('hora_programada', sa.Time(), nullable=False),
    sa.Column('prioridad', sa.Enum('normal', 'urgente', name='prioridadtrabajo'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'realizado', 'cancelado', name='estadotrabajo'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('duracion_min', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('detalle_trabajo', sa.Text(), nullable=True),
    sa.Column('fecha_realizado', sa.Date(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trabajos_cliente_id'), 'trabajos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_trabajos_codigo'), 'trabajos', ['codigo'], unique=True)
    op.create_index(op.f('ix_trabajos_estado'), 'trabajos', ['estado'], unique=False)
    op.create_index(op.f('ix_trabajos_fecha_programada'), 'trabajos', ['fecha_programada'], unique=False)
    op.create_index(op.f('ix_trabajos_fecha_realizado'), 'trabajos', ['fecha_realizado'], unique=False)
    op.create_index(op.f('ix_trabajos_id'), 'trabajos', ['id'], unique=False)
    op.create_table('interacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('trabajo_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('reclamo', 'consulta', 'llamado', 'otro', name='tipointeraccion'), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.Column('resolucion', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['trabajo_id'], ['trabajos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interacciones_cliente_id'), 'interacciones', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_interacciones_id'), 'interacciones', ['id'], unique=False)
    op.create_index(op.f('ix_interacciones_tipo'), 'interacciones', ['tipo'], unique=False)
    op.create_table('trabajo_etiquetas',
    sa.Column('trabajo_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiquetas.id'], ),
    sa.ForeignKeyConstraint(['trabajo_id'], ['trabajos.id'], ),
    sa.PrimaryKeyConstraint('trabajo_id', 'etiqueta_id')
    )
    op.create_table('interaccion_etiquetas',
    sa.Column('interaccion_id', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etiqueta_id'], ['etiquetas.id'], ),
    sa.ForeignKeyConstraint(['interaccion_id'], ['interacciones.id'], ),
    sa.PrimaryKeyConstraint('interaccion_id', 'etiqueta_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interaccion_etiquetas')
    op.drop_table('trabajo_etiquetas')
    op.drop_index(op.f('ix_interacciones_tipo'), table_name='interacciones')
    op.drop_index(op.f('ix_interacciones_id'), table_name='interacciones')
    op.drop_index(op.f('ix_interacciones_cliente_id'), table_name='interacciones')
    op.drop_table('interacciones')
    op.drop_index(op.f('ix_trabajos_id'), table_name='trabajos')
    op.drop_index(op.f('ix_trabajos_fecha_realizado'), table_name='trabajos')
    op.drop_index(op.f('ix_trabajos_fecha_programada'), table_name='trabajos')
    op.drop_index(op.f('ix_trabajos_estado'), table_name='trabajos')
    op.drop_index(op.f('ix_trabajos_codigo'), table_name='trabajos')
    op.drop_index(op.f('ix_trabajos_cliente_id'), table_name='trabajos')
    op.drop_table('trabajos')
    op.drop_index(op.f('ix_contratos_id'), table_name='contratos')
    op.drop_index(op.f('ix_contratos_cliente_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_tecnicos_id'), table_name='tecnicos')
    op.drop_table('tecnicos')
    op.drop_index(op.f('ix_servicios_id'), table_name='servicios')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_etiquetas_nombre'), table_name='etiquetas')
    op.drop_index(op.f('ix_etiquetas_id'), table_name='etiquetas')
    op.drop_table('etiquetas')
    op.drop_index(op.f('ix_clientes_nombre'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_estado'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
