"""agregar email a tecnicos

Revision ID: f0f4cdfbeea6
Revises: 9adf5c7f9715
Create Date: 2026-08-19 19:49:43.641735

"""
from alembic import op
import sqlalchemy as sa


revision = 'f0f4cdfbeea6'
down_revision = '9adf5c7f9715'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tecnicos', sa.Column('email', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tecnicos', 'email')
    # ### end Alembic commands ###
